### ISSUE TITLE
ContrastSDK.getProfileDefaultOrganizations issue

### ISSUE THREAD

**Issue by agiroshanark** [Contrast-Security-OSS/contrast-sdk-java#25]
Hello,

I have Contrast CE and I was trying to connect Contrast using the SDK but got below error:

2019-03-25 11:08:34,074 ERROR [http-nio-7990-exec-4] iroshana @10FOL89x668x4425x0 13cni51 0:0:0:0:0:0:0:1 "POST /rest/teamserver-admin/1.0/verifyconnection HTTP/1.1" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at com.contrastsecurity.sdk.ContrastSDK.getProfileDefaultOrganizations(ContrastSDK.java:208)
	at com.contrastsecurity.resource.ConfigResource.testConnection(ConfigResource.java:79)
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)

Thanks,
Iroshana

**Comment by andersonshatch** [comment]
I think your `teamServerUrl` parameter could be incorrect.
For Community Edition, you should be passing `https://ce.contrastsecurity.com/Contrast/api`

**Comment by agiroshanark** [comment]
Thanks.
